# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: AutoSD LoLa Image

on:
  workflow_dispatch:

jobs:
  build:
    name: Build AutoSD10 Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: autosd/build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y podman curl
      
      - name: Install auto-image-builder.sh
        run: |
          curl -o auto-image-builder.sh "https://gitlab.com/CentOS/automotive/src/automotive-image-builder/-/raw/main/auto-image-builder.sh"
          chmod +x auto-image-builder.sh

      - name: Build simple.aib.yml
        run: |
          sudo ./auto-image-builder.sh build \
          --distro autosd10 \
          --target qemu \
          --export qcow2 \
          --define-file vars-devel.yml \
          lola-demo.aib.yml \
          disk.qcow2
      
      - name: Upload autosd disk image file
        uses: actions/upload-artifact@v4
        with:
          name: autosd9-qemu-lola-x86_64.qcow2
          path: disk.qcow2
          retention-days: 1
          if-no-files-found: error
